node.id=3
process.roles=broker,controller
listeners=PLAINTEXT://localhost:9096,CONTROLLER://localhost:9097
advertised.listeners=PLAINTEXT://localhost:9096,CONTROLLER://localhost:9097
listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
inter.broker.listener.name=PLAINTEXT
controller.listener.names=CONTROLLER
controller.quorum.voters=1@localhost:9093,2@localhost:9095,3@localhost:9097
log.dirs=/tmp/kraft-logs-3
